# Generated by Django 5.2.1 on 2025-05-29 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.TextField()),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True)),
                ('documento_adicional', models.TextField(blank=True, null=True)),
                ('preferencias_arancelarias', models.TextField(blank=True, null=True)),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='arancel.capitulo')),
            ],
        ),
        migrations.AddField(
            model_name='capitulo',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='arancel.seccion'),
        ),
        migrations.CreateModel(
            name='Subpartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.TextField()),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True)),
                ('documento_adicional', models.TextField(blank=True, null=True)),
                ('preferencias_arancelarias', models.TextField(blank=True, null=True)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subpartidas', to='arancel.partida')),
            ],
        ),
    ]
