# Generated by Django 5.2.1 on 2025-06-02 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arancel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
    ]
