# Generated by Django 5.2.1 on 2025-06-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arancel', '0002_capitulo_descripcion_alter_capitulo_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='despacho_en_frontera',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partida',
            name='ga',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='partida',
            name='ice_iehd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subpartida',
            name='despacho_en_frontera',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subpartida',
            name='ga',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subpartida',
            name='ice_iehd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
