# Generated by Django 5.2.1 on 2025-06-03 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arancel', '0003_partida_despacho_en_frontera_partida_ga_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='despacho_en_frontera',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='documento_adicional',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='ga',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='ice_iehd',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='preferencias_arancelarias',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='unidad_medida',
        ),
    ]
