# Generated by Django 5.2.1 on 2025-06-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arancel', '0004_remove_partida_despacho_en_frontera_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subpartida',
            name='documento_adicional',
        ),
        migrations.RemoveField(
            model_name='subpartida',
            name='preferencias_arancelarias',
        ),
        migrations.AddField(
            model_name='subpartida',
            name='ace_22_chile',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subpartida',
            name='ace_22_prot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subpartida',
            name='ace_66_mexico',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subpartida',
            name='can_ace_36_47_ven',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subpartida',
            name='disposicion_legal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subpartida',
            name='entidad_que_emite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subpartida',
            name='tipo_de_doc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
