# Generated by Django 5.2.1 on 2025-06-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arancel', '0005_remove_subpartida_documento_adicional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subpartida',
            name='ga',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='subpartida',
            name='ice_iehd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
