# Generated by Django 5.2.1 on 2025-06-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arancel', '0006_alter_subpartida_ga_alter_subpartida_ice_iehd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subpartida',
            name='codigo',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
