# Generated by Django 5.2.1 on 2025-06-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arancel', '0008_alter_subpartida_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='codigo',
            field=models.CharField(max_length=15),
        ),
    ]
