# Generated by Django 5.2.1 on 2025-06-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arancel', '0009_alter_capitulo_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='subpartida',
            name='codigo',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
