# Generated by Django 5.2.1 on 2025-06-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arancel', '0011_alter_subpartida_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subpartida',
            name='codigo',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
