# Generated by Django 5.2.1 on 2025-06-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arancel', '0013_alter_subpartida_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subpartida',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
