# Generated by Django 5.2.1 on 2025-10-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arancel', '0014_alter_partida_id_alter_subpartida_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpartida',
            name='fecha_vigencia_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subpartida',
            name='fecha_vigencia_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='codigo',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='subpartida',
            name='codigo',
            field=models.CharField(db_index=True, max_length=13, unique=True),
        ),
    ]
