# Generated by Django 5.2.1 on 2025-11-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arancel', '0015_subpartida_fecha_vigencia_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpartida',
            name='detalle_cupo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subpartida',
            name='detalle_licencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subpartida',
            name='detalle_permiso',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subpartida',
            name='entidad_cupo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subpartida',
            name='entidad_licencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subpartida',
            name='entidad_permiso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subpartida',
            name='instrucciones_validacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subpartida',
            name='requiere_cupo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subpartida',
            name='requiere_licencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subpartida',
            name='requiere_permiso',
            field=models.BooleanField(default=False),
        ),
    ]
