# Generated by Django 5.2.1 on 2025-11-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arancel', '0016_subpartida_detalle_cupo_subpartida_detalle_licencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpartida',
            name='estado_cupo',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('no_aplica', 'No Aplica')], default='no_aplica', max_length=20),
        ),
        migrations.AddField(
            model_name='subpartida',
            name='estado_licencia',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('no_aplica', 'No Aplica')], default='no_aplica', max_length=20),
        ),
        migrations.AddField(
            model_name='subpartida',
            name='estado_permiso',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('no_aplica', 'No Aplica')], default='no_aplica', max_length=20),
        ),
    ]
