"""
Django settings for SCMAA project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
        
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-c@i7n+gr)68k&@374a^-(*q_15imo35e7-(i*=+gp^yn+gojjv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Permitir acceso desde cualquier IP (para desarrollo en red local)
# En producción, especifica solo los dominios permitidos
ALLOWED_HOSTS = ['*']  # Para desarrollo: permite cualquier host
# Para producción usa: ALLOWED_HOSTS = ['tudominio.com', 'www.tudominio.com']

# Configuración para funcionar detrás de proxy (ngrok, etc.)
# Permite que Django reconozca solicitudes HTTPS a través de proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# Orígenes confiables para CSRF (necesario para ngrok y otros proxies)
# En desarrollo, permite cualquier origen si DEBUG está activo
# Para ngrok, agrega tu URL específica aquí cuando la obtengas
# Ejemplo: CSRF_TRUSTED_ORIGINS = ['https://abc123.ngrok.io']
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

# Configuración de cookies para desarrollo (detrás de proxy)
if DEBUG:
    CSRF_COOKIE_SECURE = False  # Permitir cookies CSRF en HTTP (ngrok usa HTTPS pero proxy es HTTP)
    SESSION_COOKIE_SECURE = False  # Permitir cookies de sesión en HTTP


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'central',
    'arancel',
]

# Configurar middleware según el modo
if DEBUG:
    # En desarrollo, usar middleware personalizado que permite orígenes dinámicos
    CSRF_MIDDLEWARE = 'SCMAA.middleware.DynamicCsrfMiddleware'
else:
    # En producción, usar el middleware estándar
    CSRF_MIDDLEWARE = 'django.middleware.csrf.CsrfViewMiddleware'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    CSRF_MIDDLEWARE,  # Middleware CSRF (dinámico en desarrollo, estándar en producción)
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SCMAA.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SCMAA.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/La_Paz'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'
