# Generated by Django 5.2.1 on 2025-11-30 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0003_reporte_trazabilidad'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reporte',
            new_name='central_rep_usuario_d376a5_idx',
            old_name='central_rep_usuario_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='reporte',
            new_name='central_rep_codigo__3e80ad_idx',
            old_name='central_rep_codigo_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='reporte',
            new_name='central_rep_tipo_ac_38dc0e_idx',
            old_name='central_rep_accion_fecha_idx',
        ),
    ]
