# Generated by Django 5.2.1 on 2025-11-30 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0004_rename_central_rep_usuario_fecha_idx_central_rep_usuario_d376a5_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_accion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tipo_accion', models.CharField(choices=[('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('busqueda', 'Búsqueda'), ('consulta', 'Consulta de Detalle'), ('modificacion', 'Modificación'), ('eliminacion', 'Eliminación'), ('creacion', 'Creación')], db_index=True, max_length=50)),
                ('descripcion', models.TextField(help_text='Descripción detallada de la acción')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('detalles_adicionales', models.JSONField(blank=True, default=dict, help_text='Información adicional en formato JSON')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacora_entradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada de Bitácora',
                'verbose_name_plural': 'Bitácora de Auditoría',
                'ordering': ['-fecha_accion'],
                'indexes': [models.Index(fields=['usuario', '-fecha_accion'], name='central_bit_usuario_f6252a_idx'), models.Index(fields=['tipo_accion', '-fecha_accion'], name='central_bit_tipo_ac_af88ca_idx'), models.Index(fields=['-fecha_accion'], name='central_bit_fecha_a_21f6ec_idx')],
            },
        ),
    ]
